version: '3.8'

services:
  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - staticfiles:/app/static
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build: .
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - staticfiles:/app/static
    env_file: .env

volumes:
  caddy_data:
  caddy_config:
  staticfiles:
